shifu/apps/editor/forms.py
from flask_wtf import Form 
from wtforms import StringField
from wtforms.widgets import TextArea

class EditorForm(Form):

	content = StringField('WebContent',widget=TextArea())

shifu/apps/editor/__init__.py
from flask import Blueprint

editor = Blueprint('editor',__name__,static_folder='static',template_folder='templates')

from views import *

shifu/apps/editor/views.py
from flask import session,url_for,render_template,redirect,request,make_response

from apps.editor import editor
from apps import database
from apps import Sessions
from apps import env
from apps import nocache,login_required

from forms import *

from apps.pages.db import PagesDAO
from apps.website.db import StructureDAO,ThemeDAO

import bleach
import markdown

sessions = Sessions()

'''
@editor.route('/')
def edit():
	if 'username' in session:
		return render_template('editor.html',form=EditorForm())
	else:
		return redirect( url_for('users.signin') )

@editor.route('/live',methods=['GET','POST'])
def live():
	if request.method=='POST':
		form = EditorForm(request.form)

		if form.validate():
			if form.content.data != "":
				
				safe_md = bleach.clean(form.content.data,strip=True)

				parsed_html = markdown.markdown(safe_md)

				return render_template('live.html',data=parsed_html)
			else:
				return render_template('live.html',data="lorem ipsum")
		else:
			return render_template('editor.html',form=form,error='invalid validation')

'''
@editor.route('/add/<path:path>',methods=['GET','POST'])
@nocache
@login_required
def add_content(path):

	obj_pages = PagesDAO(database)
	obj_structure = StructureDAO(database)

	page = obj_pages.get_page_from_url(path)

	if page is not None:
		
		structure = obj_structure.get_structure(page['structure']['name'])

		#structure for passing in templates
		structure_inputs = structure['content']
		inputs = {}
		for fieldname in structure_inputs:
			inputs[fieldname] = {}
			inputs[fieldname]['type']=structure_inputs[fieldname]
			if structure_inputs[fieldname] == "iterator-markdown" or structure_inputs[fieldname] == "iterator-text":
				inputs[fieldname]['data'] = [""]
				inputs[fieldname]['error'] = []
			else:
				inputs[fieldname]['data'] = ""
				inputs[fieldname]['error'] = ""

		if structure is not None:
			
			if request.method == 'GET':
				return render_template('add-content.html',inputs=inputs,page=page,path=path)

			else:
				# setting bleach settings
				# allowing some tags and attributes
				alw_tags = ['img','span','h1','h2','h3','h4','h5','h6','a','li','ol','ul','abbr','acroynm','b','blockquote','code','em','i','strong','table','tr','td']
				alw_attr = { '*':['class','id'], 'img':['alt','src','style'], 'span':['style'],'a':['href']}

				# content initialised
				content = {}
				#process data
				for fieldname in structure_inputs:
										
					if structure_inputs[fieldname] == "iterator-markdown" or structure_inputs[fieldname] == "iterator-text":
						inputs[fieldname]['data'] = request.form.getlist(fieldname)
						
						content[fieldname] = []

						for md in inputs[fieldname]['data']:
							#bleaching the data
							md = bleach.clean(md,tags=alw_tags,attributes=alw_attr,strip=True)

							if structure_inputs[fieldname] == "iterator-markdown":
								html = markdown.markdown(md)
							else:
								#for simple text we do not want to convert it to html
								html = md

							data = {'html':html,'markdown':md}
							content[fieldname].append(data)

					else:
						inputs[fieldname]['data'] = request.form[fieldname]
						
						md = bleach.clean(inputs[fieldname]['data'],tags=alw_tags,attributes=alw_attr,strip=True)

						if structure_inputs[fieldname] == "simple-markdown":
							html = markdown.markdown(md)
						else:
							#for simple text we do not want to convert it to html
							html = md

						content[fieldname] = {'html':html,'markdown':md}

				if obj_pages.add_page_content(path,content,sessions.logged_in()) is True:
					if env.check_indexset() is False:
						env.set_indexpage(page['_id'])
					return redirect( url_for('users.admin') )
				else:
					return render_template('add-content.html',inputs=inputs,page=page,path=path)

		else:
			print "structure not found"
			return redirect( url_for('users.admin') )

	else:
		print "page not found"
		return redirect( url_for('users.admin') )



@editor.route('/edit/<path:path>',methods=['GET','POST'])
@nocache
@login_required
def edit_content(path):
	
	obj_pages = PagesDAO(database)
	obj_structure = StructureDAO(database)

	page = obj_pages.get_page_from_url(path)

	if page is not None:
		
		structure = obj_structure.get_structure(page['structure']['name'])

		#structure for passing in templates
		structure_inputs = structure['content']
		inputs = {}
		for fieldname in page['structure']['content']:
			inputs[fieldname] = {}
			inputs[fieldname]['type']=structure_inputs[fieldname]
			if (structure_inputs[fieldname] == "iterator-markdown") or (structure_inputs[fieldname] == "iterator-text"):
				inputs[fieldname]['data'] = []
				for item in page['structure']['content'][fieldname]:
					inputs[fieldname]['data'].append(item['markdown'])
			else:
				inputs[fieldname]['data'] = page['structure']['content'][fieldname]['markdown']
				
			

		if structure is not None:
			
			if request.method == 'GET':
				return render_template('edit-content.html',inputs=inputs,page=page,path=path)

			else:
				content = {}
				#process data
				for fieldname in structure_inputs:
										
					if structure_inputs[fieldname] == "iterator-markdown" or structure_inputs[fieldname] == "iterator-text":
						inputs[fieldname]['data'] = request.form.getlist(fieldname)
						
						content[fieldname] = []

						for md in inputs[fieldname]['data']:
							#bleaching the data
							md = bleach.clean(md,strip=True)

							if structure_inputs[fieldname] == "iterator-markdown":
								html = markdown.markdown(md)
							else:
								#for simple text we do not want to convert it to html
								html = md

							data = {'html':html,'markdown':md}
							content[fieldname].append(data)

					else:
						inputs[fieldname]['data'] = request.form[fieldname]
						
						md = bleach.clean(inputs[fieldname]['data'],strip=True)

						if structure_inputs[fieldname] == "simple-markdown":
							html = markdown.markdown(md)
						else:
							#for simple text we do not want to convert it to html
							html = md

						content[fieldname] = {'html':html,'markdown':md}

				if obj_pages.edit_page_content(path,content,sessions.logged_in()) is True:
					return redirect( url_for('users.admin') )
				else:
					return render_template('edit-content.html',inputs=inputs,page=page,path=path)

		else:
			print "structure not found"
			return redirect( url_for('users.admin') )

	else:
		print "page not found"
		return redirect( url_for('users.admin') )

shifu/apps/editor/templates/add-content.html
{% extends "dashboard-layout.html" %}


{% block title %}
{{ super() }}-New Page
{% endblock %}

{% block includes %}
{{ super() }}
<link type="text/css" rel="stylesheet" href="{{ url_for('editor.static', filename='css/edit-content.css' ) }}" />
    
    <script type="text/javascript">
        function createtextinstance(obj)
        {
            var newinstanceHTML = '<div class="instance"><textarea class="textbox" name="';
            newinstanceHTML +=obj.parentNode.children[0].children[0].name;
            newinstanceHTML +='"></textarea><button class="btn"  onclick="removetextinstance(this)"><a><i class="glyphicon glyphicon-remove-sign"></a></i></button></div>';
            
            var instance = document.createElement('div');
            instance.innerHTML = newinstanceHTML;
            //var instance = document.createElement(newinstance);
            var editorDiv = obj.parentNode;
            editorDiv.insertBefore(instance.firstChild,obj);
        }
        
        function removetextinstance(obj)
        {
            var editorDiv = obj.parentNode;
            editorDiv.remove();
            
        }
        
        function createinputinstance(obj)
        {
            var newinstanceHTML = '<div class="col-sm-12"><div class="input-group col-sm-12"><input type="text" class="form-control container-input" id="inputlink" name="';

            newinstanceHTML += obj.parentNode.children[0].children[0].name;
            newinstanceHTML += '"><span class="input-group-addon glyphicon glyphicon-remove-sign glyphi" onclick="removeinputinstance(this)"><a></a></span></div><span class="help-block"></span></div>';

            var instance = document.createElement('div');
            instance.innerHTML = newinstanceHTML;
            //var instance = document.createElement(newinstance);
            var editorDiv = obj.parentNode;
            editorDiv.insertBefore(instance.firstChild,obj);
        }
        
        function removeinputinstance(obj)
        {
            var editorDiv = obj.parentNode.parentNode;
            editorDiv.remove();
            
        }
    </script>

{% endblock %}

{% block content %}

 <div class="editor-area">
    <form method="post" action="{{ url_for('editor.add_content',path=path) }}">
            <!-- ====== heading ======-->
            <div class="heading">
                <h3 class="heading-text">{{ page['page-name'] }} : Add Content</h3>
                <input type="submit" class="btn code-red top-button" value="Publish">
                <button class="btn code-red top-button"><i class="glyphicon glyphicon-eye-open"></i> Live Preview</button>
            </div>
            <hr class="header-line" />
            
        <!-- ========options required for floating========= -->
        <div class="edit-option-bar" id="edit-option-bar" >
        <!-- Nav tabs -->
            <ul class="nav nav-pills nav-justified" id="myTab">

                {% for field_name in inputs %}
                    {% if loop.index0 == 0 %}
                        <li class="active"><a class="opt" href="#{{ field_name }}" data-toggle="pill" >{{ field_name }}</a></li>
                    {% else %}
                        <li><a class="opt" href="#{{ field_name }}" data-toggle="pill" >{{ field_name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        
        <div class="related-divs">
            <!-- Tab panes -->
            <div class="tab-content" id="myTabContent">
            
            {% for field_name in inputs %}

                {% if loop.index0 == 0 %}
                <div class="tab-pane fade in active" id="{{ field_name }}">
                {% else %}
                <div class="tab-pane fade" id="{{ field_name }}">
                {% endif %}

                    {% if inputs[field_name]['type'] == "iterator-markdown" %}
                        {% for instance in inputs[field_name]['data'] %}
                        <div class="instance">
                            <textarea class="textbox" name="{{ field_name }}" >{{ instance }}</textarea>
                            <button class="btn" onclick="removetextinstance(this)" ><a><i class="glyphicon glyphicon-remove-sign black"></i></a></button>
                        </div>
                        {% endfor %}

                        <span class="btn button text-instance-button green" onclick="createtextinstance(this)"><i class="glyphicon glyphicon-plus"></i>Add Instance</span>
                    {% elif inputs[field_name]['type'] == "simple-markdown" %}
                        <div class="instance">
                            <textarea class="textbox" name="{{ field_name }}">{{ inputs[field_name]['data'] }}</textarea>
                            <button class="btn" onclick="removetextinstance(this)" ><a><i class="glyphicon glyphicon-remove-sign black"></i></a></button>
                        </div>
                    {% elif inputs[field_name]['type'] == "iterator-text" %}
                        <div class="form-group">
                        {% for instance in inputs[field_name]['data'] %}
                            
                                <div class="col-sm-12">
                                    <div class="input-group col-sm-12">
                                        <input type="text" class="form-control container-input" name="{{ field_name }}" value = "{{ instance }}">
                                        <span class="input-group-addon glyphicon glyphicon-remove-sign glyphi" onclick="removeinputinstance(this)" ></span>
                                    </div>
                                    <span class="help-block"></span>

                                
                               </div>
                            
                        {% endfor %}
                            <span class="btn button input-instance-button green" onclick="createinputinstance(this)"><i class="glyphicon glyphicon-plus"></i>Add Instance</span>

                            </div>
                    {% else %}
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <div class="input-group col-sm-12">
                                        <input type="text" class="form-control container-input" name="{{ field_name }}" value="{{ inputs[field_name]['data'] }}">
                                    </div>
                                    <span class="help-block"></span>
                               </div>
                            </div>
                        

                    {% endif %}
                </div>
            {% endfor %}

            </div>
        </div>
    </form>         
</div>


   
   	
{% endblock %}

shifu/apps/editor/templates/edit-content.html
{% extends "dashboard-layout.html" %}


{% block title %}
{{ super() }}-New Page
{% endblock %}

{% block includes %}
{{ super() }}
<link type="text/css" rel="stylesheet" href="{{ url_for('editor.static', filename='css/edit-content.css' ) }}" />
    
    <script type="text/javascript">
        function createtextinstance(obj)
        {
            var newinstanceHTML = '<div class="instance"><textarea class="textbox" name="';
            newinstanceHTML +=obj.parentNode.children[0].children[0].name;
            newinstanceHTML +='"></textarea><button class="btn"  onclick="removetextinstance(this)"><a><i class="glyphicon glyphicon-remove-sign"></a></i></button></div>';
            
            var instance = document.createElement('div');
            instance.innerHTML = newinstanceHTML;
            //var instance = document.createElement(newinstance);
            var editorDiv = obj.parentNode;
            editorDiv.insertBefore(instance.firstChild,obj);
        }
        
        function removetextinstance(obj)
        {
            var editorDiv = obj.parentNode;
            editorDiv.remove();
            
        }
        
        function createinputinstance(obj)
        {
            var newinstanceHTML = '<div class="col-sm-12"><div class="input-group col-sm-12"><input type="text" class="form-control container-input" id="inputlink" name="';

            newinstanceHTML += obj.parentNode.children[0].children[0].children[0].name;
            newinstanceHTML += '"><span class="input-group-addon glyphicon glyphicon-remove-sign glyphi" onclick="removeinputinstance(this)"><a></a></span></div><span class="help-block"></span></div>';

            var instance = document.createElement('div');
            instance.innerHTML = newinstanceHTML;
            //var instance = document.createElement(newinstance);
            var editorDiv = obj.parentNode;
            editorDiv.insertBefore(instance.firstChild,obj);
        }
        
        function removeinputinstance(obj)
        {
            var editorDiv = obj.parentNode.parentNode;
            editorDiv.remove();
            
        }
    </script>

{% endblock %}

{% block content %}

 <div class="editor-area">
    <form method="post" action="{{ url_for('editor.add_content',path=path) }}">
            <!-- ====== heading ======-->
            <div class="heading">
                <h3 class="heading-text">{{ page['page-name'] }} : Edit Content</h3>
                <input type="submit" class="btn code-red top-button" value="Publish">
                <button class="btn code-red top-button"><i class="glyphicon glyphicon-eye-open"></i> Live Preview</button>
            </div>
            <hr class="header-line" />
            
        <!-- ========options required for floating========= -->
        <div class="edit-option-bar" id="edit-option-bar" >
        <!-- Nav tabs -->
            <ul class="nav nav-pills nav-justified" id="myTab">

                {% for field_name in inputs %}
                    {% if loop.index0 == 0 %}
                        <li class="active"><a class="opt" href="#{{ field_name }}" data-toggle="pill" >{{ field_name }}</a></li>
                    {% else %}
                        <li><a class="opt" href="#{{ field_name }}" data-toggle="pill" >{{ field_name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        
        <div class="related-divs">
            <!-- Tab panes -->
            <div class="tab-content" id="myTabContent">
            
            {% for field_name in inputs %}

                {% if loop.index0 == 0 %}
                <div class="tab-pane fade in active" id="{{ field_name }}">
                {% else %}
                <div class="tab-pane fade" id="{{ field_name }}">
                {% endif %}

                    {% if inputs[field_name]['type'] == "iterator-markdown" %}
                        {% for instance in inputs[field_name]['data'] %}
                        <div class="instance">
                            <textarea class="textbox" name="{{ field_name }}" >{{ instance }}</textarea>
                            <button class="btn" onclick="removetextinstance(this)" ><a><i class="glyphicon glyphicon-remove-sign black"></i></a></button>
                        </div>
                        {% endfor %}

                        <span class="btn button text-instance-button green" onclick="createtextinstance(this)"><i class="glyphicon glyphicon-plus"></i>Add Instance</span>
                    {% elif inputs[field_name]['type'] == "simple-markdown" %}
                        <div class="instance">
                            <textarea class="textbox" name="{{ field_name }}">{{ inputs[field_name]['data'] }}</textarea>
                            <button class="btn" onclick="removetextinstance(this)" ><a><i class="glyphicon glyphicon-remove-sign black"></i></a></button>
                        </div>
                    {% elif inputs[field_name]['type'] == "iterator-text" %}
                        <div class="form-group">
                        {% for instance in inputs[field_name]['data'] %}
                            
                                <div class="col-sm-12">
                                    <div class="input-group col-sm-12">
                                        <input type="text" class="form-control container-input" name="{{ field_name }}" value = "{{ instance }}">
                                        <span class="input-group-addon glyphicon glyphicon-remove-sign glyphi" onclick="removeinputinstance(this)" ></span>
                                    </div>
                                    <span class="help-block"></span>

                                
                                </div>
                        {% endfor %}
                                    <span class="btn button input-instance-button green" onclick="createinputinstance(this)"><i class="glyphicon glyphicon-plus"></i>Add Instance</span>
                            </div>
                    {% else %}
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <div class="input-group col-sm-12">
                                        <input type="text" class="form-control container-input" name="{{ field_name }}" value="{{ inputs[field_name]['data'] }}">
                                    </div>
                                    <span class="help-block"></span>
                               </div>
                            </div>
                        

                    {% endif %}
                </div>
            {% endfor %}

            </div>
        </div>
    </form>         
</div>


   
    
{% endblock %}

shifu/apps/editor/templates/editor.html
{% extends 'layout.html' %}

{% block title %}
{{ super() }}-editor
{% endblock %}

{% block includes %}
{{ super() }}
<link rel="stylesheet" href=" {{ url_for('editor.static',filename='css/editor_style.css') }}">
{% endblock %}

{% block content %}
	<div class="editor_wrapper">
		<form method="post" action=" {{ url_for('.live') }}">
			{{ form.hidden_tag() }}

			{{ form.content(rows=10,cols=50) }}
			{% if form.content.error %}
				{{ form.content.error }}
			{% endif %}
			<br />
			<input type="submit" value="publish">
		</form>
	</div>
{% endblock %}

shifu/apps/editor/templates/live.html
{% extends 'base-layout.html' %}

{% block title %}
{{ super() }}-live
{% endblock %}

{% block includes %}
{% endblock %}

{% block content %}
{{ data|safe }}
{% endblock %}